title: EAS Consulting
author: Eli Sachs
email: easachs13@gmail.com
description: >-
  "You miss 100% of the shots you don't take." - Wayne Gretzky
baseurl: ""
url: "https://www.easachs.com"

github_username:  easachs
linkedin_username: easachs

google_analytics: "G-RS80H21YWV"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:title

header_pages:
- _pages/about.md
- _pages/resume.html
- _pages/portfolio.md
- _pages/contact.html
